/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        loto: ["Lato", "Lato-sans-serif"],
        jp: ["Noto Sans JP", "sans-serif"],
        maru: ["Zen Maru Gothic", "sans-serif"],
      },
      backgroundImage: {
        arrow: "url(../src/assets/images/downArrow.webp)",
        one: "url(../src/assets/images/ink/one.webp)",
        two: "url(../src/assets/images/ink/two.webp)",
        three: "url(../src/assets/images/ink/three.webp)",
        four: "url(../src/assets/images/ink/four.webp)",
        five: "url(../src/assets/images/ink/five.webp)",
        six: "url(../src/assets/images/ink/six.webp)",
        seven: "url(../src/assets/images/ink/seven.webp)",
        eight: "url(../src/assets/images/ink/eight.webp)",
        nine: "url(../src/assets/images/ink/nine.webp)",
        ten: "url(../src/assets/images/ink/ten.webp)",
        twoOne: "url(../src/assets/images/ink/twoOne.webp)",
        twoTwo: "url(../src/assets/images/ink/twoTwo.webp)",
        twoThree: "url(../src/assets/images/ink/twoThree.webp)",
        twoFour: "url(../src/assets/images/ink/twoFour.webp)",
        twoFive: "url(../src/assets/images/ink/twoFive.webp)",
        twoSix: "url(../src/assets/images/ink/twoSix.webp)",
        gray: "url(../src/assets/images/head/gray.webp)",
        ghost: "url(../src/assets/images/head/Ghost.webp)",
        change: "url(../src/assets/images/change.webp)",
        true: "url(../src/assets/images/trueGreen.webp)",
        titleTrue: "url(../src/assets/images/titleTrue.webp)",
        next: "url(../src/assets/images/next.webp)",
        batu: "url(../src/assets/images/batu.webp)",
        create: "url(../src/assets/images/create.png)",
        st: "url(../src/assets/images/create/st.png)",
        sennsi: "url(../src/assets/images/create/sennsi.png)",
        noSelect: "url(../src/assets/images/noSelect.webp)",
        confirmTitle: "url(../src/assets/images/ink/confirmTitle.webp)",
        confirmPurple: "url(../src/assets/images/ink/confirmPurple.webp)",
        topback: "url(../src/assets/images/create/topback.webp)",
        bgFour: "url(../src/assets/images/columnSlide/imagefour.webp)",
      },
      backgroundSize: {
        auto: "auto",
        cover: "cover",
        contain: "contain",
        "50%": "50%",
        16: "4rem",
      },
      keyframes: {
        appears: {
          "0%": { opacity: 0 },
          "100%": { opacity: 1 },
        },
        disappear: {
          "0%": { opacity: 1 },
          "100%": { opacity: 0 },
        },
      },
      animation: {
        appearOne: "appears 1s ease-out .5s infinite",
        appearTwo: "appears 1s ease-out .3s infinite",
        appearThree: "appears 1s linear .1s infinite",
        appearFour: "appears 1s linear .1s infinite alternate",
        appearFive: "appears 1s linear .3s infinite alternate",
        appearSix: "appears 1s linear .5s infinite alternate",
      },
    },
  },
  plugins: [],
};
